# Generated by Django 6.0.3 on 2026-05-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpSorage',
        ),
    ]
