# Generated by Django 6.0.3 on 2026-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_otpsorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpSorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('otp', models.CharField(max_length=6)),
                ('otp_sent_time', models.IntegerField()),
                ('otp_unique_id', models.TextField()),
            ],
        ),
    ]
