# Generated by Django 6.0.4 on 2026-05-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_allbackuphistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbackuphistory',
            name='rank',
        ),
    ]
