# Generated by Django 6.0.4 on 2026-05-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_allbackuphistory_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbackuphistory',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
